# Frontend Service — ClusterIP (now exposed via Ingress)
apiVersion: v1
kind: Service
metadata:
  name: python-frontend-svc
  namespace: python-demo
  labels:
    app: python-frontend
spec:
  type: ClusterIP
  selector:
    app: python-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
