# Spring Boot Backend Service — ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: springboot-backend-svc
  namespace: java-react-demo
  labels:
    app: springboot-backend
spec:
  type: ClusterIP
  selector:
    app: springboot-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
