# React Frontend Service — NodePort
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-svc
  namespace: java-react-demo
  labels:
    app: react-frontend
spec:
  type: NodePort
  selector:
    app: react-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090          # access via http://<NODE_IP>:30090
      protocol: TCP
